config/routes.rb
Rails.application.routes.draw do
  # get 'admins/index'
  # get 'admins/show'
  # get 'admins/new'
  # get 'admins/edit'
  # get 'admins/destroy'
  resources :admins
  resources :users
  get 'manage/index'
  get 'manage/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "manage#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
    # For display all admins information.
  def index
    @admin = Admin.all
  end

    # For only one admin by his id
  def show
    @admin = Admin.find(params[:id])
    # try to get this with before action
  end

  def new
    @admin = Admin.new
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:id])
    @admin.update(admin_params)
    redirect_to admin_path(@admin)
  end

  def destroy
    @admin.destroy
    redirect_to admin_path
  end


    # POST /admins or /admins.json
  def create
    @admin = Admin.new(admin_params)
    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: "Admin was successfully created." }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_params
      params.require(:admin).permit(:Fname, :Lname, :age, :salary, :position)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  def index
    # @array = ["ehmd", "ahmed", "khaled"]
  end
  def home
    # redirect_to(:controller=>"manage", :action=>"index")
    # # render "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<div class="container">
    <div class="table-responsive">
        <%= form_for(admin) do |f| %>
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="first name">First Name</label>
                        <%= f.text_field :Fname, type: "text", class: "form-control", placeholder: "First name"%>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="Last name">Last name</label>
                        <%= f.text_field :Lname, type: "text", class: "form-control", placeholder: "Last name"%>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="first name"> Age</label>
                        <%= f.number_field :age, type: "number", class: "form-control", placeholder: "age"%>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="Salary">Salary</label>
                        <%= f.text_field :salary, type: "number", class: "form-control", placeholder: "Salary"%>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="Position">Position</label>
                        <%= f.text_field :position, type: "number", class: "form-control", placeholder: "Position"%>
                    </div>
                </div>
                <div class="d-grid gap-2 d-md-block">
                    <%= f.submit class: "btn btn-primary" %>
                    <%= link_to 'show', @admin,  class: "btn btn-primary" %>
                    <%= link_to 'back', admins_path, class: "btn btn-primary"%>
                </div>
            </form>
        <% end %>
    </div>
</div>

app/views/admins/edit.html.erb
        
<div class="container">
    <div class="table-responsive">
        <h1>Admins edit</h1>
    </div>
</div>

<%= render 'form', admin: @admin %>

app/views/admins/index.html.erb
<div class="container">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-xs-6">
                        <h2><b>Users</b></h2>
                    </div>
                    <div class="col-xs-6">
                        <%= link_to 'New User', new_admin_path, class: "btn btn-success", 'data-toggle': "modal" %>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Fname</th>
                        <th>Lname</th>
                        <th>age</th>
                        <th>salary</th>
                        <th>position</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @admin.each do |admin| %>
                        <tr>
                            <td><%= admin.Fname %></td>
                            <td><%= admin.Lname %></td>
                            <td><%= admin.age %></td>
                            <td><%= admin.salary %></td>
                            <td><%= admin.position %></td>
                            <td><%= link_to 'Show', admin %></td>
                            <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
                            <td><%= button_to 'Remove', admin, method: 'delete' %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/admins/new.html.erb
<div class="container">
    <div class="table-responsive">
        <h1>Add new admin</h1>
    </div>
</div>

<%= render 'form', admin: @admin %>

app/views/admins/show.html.erb
<div class="alert alert-primary" role="alert">
    <p> <%= notice %> </p>
</div>
<div class="container">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-xs-12">
                        <h2><b><%= @admin.Fname %></b> </b> <%= @admin.Lname %></p></h2>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Age</th>
                        <th>Salary</th>
                        <th>Position</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @admin.Fname %></td>
                        <td><%= @admin.Lname %></td>
                        <td><%= @admin.age %></td>
                        <td><%= @admin.salary %></td>
                        <td><%= @admin.position %></td>
                    </tr>
                </tbody>
            </table>
            <button type="button" class="btn btn-outline-primary" ><%= link_to 'Edit', edit_admin_path %></button>
            <button type="button" class="btn btn-outline-primary"><%= link_to 'back', admins_path %></button>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admins">Home</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>